<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>TeacherOS.Api-local-development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TeacherOS.Application/TeacherOS.Application.csproj" />
    <ProjectReference Include="../TeacherOS.Infrastructure/TeacherOS.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TeacherOS.IntegrationTests" />
  </ItemGroup>
</Project>
